name 'R'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'Apache 2.0'
description 'Provides LWRP for R and CRAN'
long_description 'Provides LWRP for the R statistical computing language, as well as support for installing packages through CRAN.'
version '0.1.4'

depends 'yum'
depends 'apt'
depends 'ark'
depends 'build-essential'
depends 'readline'
